language: node_js

addons:
  apt:
    packages:
      - docker-ce

before_install:
  - sudo /etc/init.d/postgresql stop

install:
  - npm install

before_script:
  - npm run lint
  - npm run format
  - docker swarm init
  - docker service create --name registry --publish published=5000,target=5000 registry:2
  - echo "secret" | docker secret create db_password -
  - echo "secret" | docker secret create jwt_secret -
  - docker secret ls

script:
  - npm run build
  - docker-compose -f docker-compose-prod.yml build
  - docker-compose -f docker-compose-prod.yml push
  - docker stack deploy -c docker-compose-prod.yml express_ts
  - docker stack services express_ts
  - sleep 10
  - docker service logs express_ts_web
  - docker stack services express_ts
  - sleep 10
  - docker service logs express_ts_web
  - curl http://localhost:3000/
