language: node_js

services:
  - docker

before_install:
  - docker -v
  - npm install
  - npm run build
  - cp .env.example .env
  - sudo /etc/init.d/postgresql stop

install:
  - docker-compose -f docker-compose-test.yml build
  - docker-compose -f docker-compose-test.yml up -d
  - docker images
  - docker ps

script:
  - docker-compose -f docker-compose-test.yml exec web sh -c "npm test"
