language: node_js

services:
  - docker

before_install:
  - sudo /etc/init.d/postgresql stop

install:
  - npm install

before_script:
  - npm run lint
  - npm run format

script:
  - npm run build
  - docker-compose -f docker-compose-test.yml build
  - docker-compose -f docker-compose-test.yml up -d
  - sleep 10
  - curl http://localhost:3000/
  - npm test
