language: node_js

addons:
  apt:
    packages:
      - docker-ce

before_install:
  - docker -v
  - sudo /etc/init.d/postgresql stop

install:
  - npm install

before_script:
  - npm run lint
  - npm run format

script:
  - npm run build
  - docker-compose -f docker-compose-test.yml build
  - docker-compose -f docker-compose-test.yml up -d
  - sleep 10
  - docker-compose -f docker-compose-test.yml ps
  - npm test

after_script:
  - curl http://localhost:3000/
  - docker-compose -f docker-compose-test.yml down --volumes
