language: node_js

services:
  - docker

before_install:
  - sudo /etc/init.d/postgresql stop
  - npm install
  - npm run build

install:
  - docker-compose -f docker-compose-test.yml build
  - docker-compose -f docker-compose-test.yml up -d
  - docker images
  - docker ps
  - sleep 10
  - docker-compose -f docker-compose-test.yml ps
  - docker-compose -f docker-compose-test.yml logs web
  - npm run test

before_script:
  - curl http://localhost:3000/

script:
  - docker-compose -f docker-compose-test.yml exec postgres sh -c "echo "testest""
  - docker-compose -f docker-compose-test.yml exec web sh -c "ls"
