language: node_js

addons:
  apt:
    packages:
      - docker-ce

before_install:
  - docker -v
  - sudo /etc/init.d/postgresql stop

install:
  - npm install

before_script:
  - npm run lint
  - npm run format
  - npm run build

script:
  - docker-compose -f docker-compose-test.yml build
  - docker-compose -f docker-compose-test.yml up -d
  - sleep 10
  - docker-compose -f docker-compose-test.yml ps
  - docker exec -it $(docker ps -lq -f "name=express-ts-starter_web") sh -c "npm test"

after_script:
  - curl http://localhost:3000/
  - docker-compose -f docker-compose-test.yml down --volumes
