version: '3.7'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: 127.0.0.1:5000/express-ts:prod
    ports:
      - 3000:3000
    networks:
      - webnet
    depends_on:
      - postgres
    deploy:
      replicas: 4
      restart_policy:
        condition: on-failure
    environment:
      - DB_HOST=postgres
      - DB_USERNAME=prod
      - DB_PASSWORD_FILE=/run/secrets/db_password
      - DB_NAME=prod
      - JWT_SECRET_FILE=/run/secrets/jwt_secret
    secrets:
      - db_password
      - jwt_secret

  postgres:
    image: postgres:11.3-alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - webnet
    environment:
      - POSTGRES_USER=prod
      - POSTGRES_PASSWORD_FILE=/run/secrets/db_password
      - POSTGRES_DB=prod
    secrets:
      - db_password
    deploy:
      placement:
        constraints: [node.role == manager]

networks:
  webnet:

secrets:
  jwt_secret:
    external: true
  db_password:
    external: true

volumes:
  db-data:
    driver: local
